Update version bounds/travis/format cabal file
update .gitignore for cabal v2 commands
add note to README.md about cabal-edit upgradeall

fixes: https://github.com/kapralVV/Unique/issues/5
also fixes travis builds

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,49 +1,65 @@
-dist: trusty
-sudo: false
-os: linux
+env:
+ # Note: We have to use Cabal 2.4 with GHC 7.0 since for some reason
+ # builds of "text" fail with GHC 7.0 and Cabal versions prior to 2.4
+ # https://github.com/haskell/bytestring/issues/213
+ # With Cabal 2.4 we also get improved syntax in cabal.project files,
+ # supporting remote sources, and other goodies, so use it across the
+ # board.
+ - GHCVER=7.4.2 CABALVER=2.4
+ - GHCVER=7.6.3 CABALVER=2.4
+ - GHCVER=7.8.4 CABALVER=2.4
+ - GHCVER=7.10.3 CABALVER=3.2
+ - GHCVER=8.0.2 CABALVER=3.2
+ - GHCVER=8.2.2 CABALVER=3.2
+ - GHCVER=8.4.4 CABALVER=3.2
+ - GHCVER=8.6.5 CABALVER=3.2
+ - GHCVER=8.8.3 CABALVER=3.2
+ - GHCVER=8.10.1 CABALVER=3.2
+
+ ### The head in "ppa", currently 8.7, is no longer worth testing.
+ # - GHCVER=head  CABALVER=2.4
 
 language: haskell
+
 cache:
   directories:
-    - .cabal-sandbox
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
 
 matrix:
-  include:
-  - ghc: "8.10"
-    env: CACHE_NAME=CACHE8.10
-    install : cabal sandbox init && cabal install --only-dependencies --enable-tests --disable-documentation
-    script: cabal configure --enable-tests && cabal test --show-details=always
+  allow_failures:
+   - env: GHCVER=head  CABALVER=2.4
 
-  - ghc: "8.8"
-    env: CACHE_NAME=CACHE8.8
-    install : cabal sandbox init && cabal install --only-dependencies --enable-tests --disable-documentation
-    script: cabal configure --enable-tests && cabal test --show-details=always
+before_install:
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+ - cabal --version
+ - "GHCNUMVER=$(ghc --numeric-version|perl -ne '/^(\\d+)\\.(\\d+)\\.(\\d+)(\\.(\\d+))?$/; print(10000 * $1 + 100 * $2 + ($3 == 0 ? $5 != 1 : $3))')"
+ - echo $GHCNUMVER
 
-  - ghc: "8.6"
-    env: CACHE_NAME=CACHE8.6
+install:
+ - travis_retry cabal v2-update
 
-  - ghc: "8.4"
-    env: CACHE_NAME=CACHE8.4
-
-  - ghc: "8.2"
-    env: CACHE_NAME=CACHE8.2
-
-  - ghc: "8.0"
-    env: CACHE_NAME=CACHE8.0
-
-  - ghc: "7.10"
-    env: CACHE_NAME=CACHE7.10
-
-  - ghc: "7.8"
-    env: CACHE_NAME=CACHE7.8
-
-  - ghc: "7.6"
-    env: CACHE_NAME=CACHE7.6
-
-  - ghc: "7.4"
-    env: CACHE_NAME=CACHE7.4
-    install : cabal sandbox init && cabal install --only-dependencies --enable-tests --disable-documentation
-    script: cabal configure --enable-tests && cabal test --show-details=always
-
-install : cabal sandbox init && cabal install --only-dependencies --enable-tests --enable-benchmarks --disable-documentation
-script: cabal configure --enable-tests --enable-benchmarks && cabal test --show-details=always && cabal bench --benchmark-option="-obench.html"
+script:
+ - cabal v2-configure
+ - cabal v2-build
+ - cabal v2-haddock -O0
+ - cabal v2-sdist -o .
+ - cabal v2-test
+ # Remove to enable build of sdist.
+ - rm -f cabal.project
+ # Build the benchmarks and run a single iteration.
+ - if [ "$GHCNUMVER" -ge 71000 ]; then
+      (cabal v2-bench -O0);
+   fi
+ - cabal check
+ - export SRC=$(cabal info . | awk '{print $2; exit}');
+   if [ -f "$SRC.tar.gz" ]; then
+      cabal get "./$SRC.tar.gz";
+      (cd "$SRC"; cabal v2-build);
+   else
+      echo "expected '$SRC.tar.gz' not found";
+      exit 1;
+   fi
